/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare function clean(src: string): string
export declare function cleanText(src: string): string
export declare function isHtml(input: string): boolean
